const PaymentMethods = ["BKASH", "ROCKET", "NAGAD", "COD"];
const OrderStatus = [
    "PENDING",
    "RECEIVED",
    "PROCESSING",
    "SHIPPED",
    "DELIVERED",
    "DELIVERY_FAILED",
    "CANCELED_BY_CUSTOMER",
    "CANCELED_BY_SELLER",
]
const ProductTypes = ['SUBJECT_BOOK', 'ACADEMIC_BOOK', 'STATIONARY', 'FASHION']
const COUPON_TYPES = ['FIXED_CART', 'FIXED_PRODUCT']
const PhoneOTPMSG = "Your OTP is {OTP}"
const EmailOTPMSG = "Your OTP is {OTP}"

const PRODUCT_MANAGE_PERMISSIONS = ["MANAGE_PRODUCT", "SUPER_ADMIN"]
const CATEGORY_MANAGE_PERMISSIONS = ["MANAGE_PRODUCT", "SUPER_ADMIN"]
const COUPON_MANAGE_PERMISSIONS = ["MANAGE_COUPON", "SUPER_ADMIN"]
const ORDER_MANAGE_PERMISSIONS = ["MANAGE_ORDERS", "SUPER_ADMIN"]
const ADMIN_MANAGE_PERMISSIONS = ["SUPER_ADMIN"]
const BLOG_MANAGE_PERMISSIONS = ["MANAGE_BLOG", "SUPER_ADMIN"]
const SPECIAL_EXTRA_MANAGE_PERMISSION = ['MANAGE_SPECIAL_EXTRA', 'SUPER_ADMIN']
const SETTINGS_MANAGE_PERMISSION = ['MANAGE_SITE_SETTINGS', 'SUPER_ADMIN']

const OFFER_TYPES = { PRODUCT: 'PRODUCT', CATEGORY: 'CATEGORY' }

module.exports = {
    PaymentMethods,
    OrderStatus,
    ProductTypes,
    PhoneOTPMSG,
    EmailOTPMSG,
    OFFER_TYPES,
    COUPON_TYPES,
    PERMS: {
        PRODUCT_MANAGE_PERMISSIONS,
        CATEGORY_MANAGE_PERMISSIONS,
        COUPON_MANAGE_PERMISSIONS,
        ORDER_MANAGE_PERMISSIONS,
        ADMIN_MANAGE_PERMISSIONS,
        BLOG_MANAGE_PERMISSIONS,
        SPECIAL_EXTRA_MANAGE_PERMISSION,
        SETTINGS_MANAGE_PERMISSION
    }
}